# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='retried_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата повторной инициализации чека в системе оператора'),
        ),
    ]
