sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install: pip install tox-travis
script: tox
addons:
  postgresql: "9.4"
before_install:
  - pip install codecov
after_success:
  - codecov

notifications:
  email: false
